apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-native-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-native-web-app
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/vudayani-vmw/tanzu-java-native-web-app
      ref:
        branch: master
